In [1]:
import numpy as np
import pandas as pd

In [ ]:
# 1.Download a sample CSV file of IPL player stats (include columns like player name, runs, matches, and some missing values). Load it into a pandas DataFrame and use isnull() and notnull() to print how many missing values are present in each column.

In [3]:
pd.read_csv("ipl_players.csv")

    player_name    runs  matches
0   Virat Kohli  7263.0    237.0
1  Rohit Sharma  6628.0    243.0
2      MS Dhoni  5082.0      NaN
3  Shubman Gill  2790.0    103.0
4  Rishabh Pant     NaN    110.0

In [4]:
df = pd.read_csv("ipl_players.csv")

In [5]:
df

    player_name    runs  matches
0   Virat Kohli  7263.0    237.0
1  Rohit Sharma  6628.0    243.0
2      MS Dhoni  5082.0      NaN
3  Shubman Gill  2790.0    103.0
4  Rishabh Pant     NaN    110.0

In [6]:
df.isnull().sum()

player_name    0
runs           1
matches        1
dtype: int64

In [7]:
df.notnull().sum()

player_name    5
runs           4
matches        4
dtype: int64

In [8]:
# 2.Using the loaded IPL player stats DataFrame, apply dropna(axis=0, how='any') to remove all rows with any missing data and display the shape of the DataFrame before and after dropping.

In [9]:
df.shape

(5, 3)

In [10]:
df.dropna(axis=0, how="any")

    player_name    runs  matches
0   Virat Kohli  7263.0    237.0
1  Rohit Sharma  6628.0    243.0
3  Shubman Gill  2790.0    103.0

In [21]:
df_clean = df.dropna(axis=0, how="any")

In [22]:
df_clean

    player_name    runs  matches
0   Virat Kohli  7263.0    237.0
1  Rohit Sharma  6628.0    243.0
3  Shubman Gill  2790.0    103.0

In [29]:
df_clean.shape

(3, 3)

In [24]:
df_clean

    player_name    runs  matches
0   Virat Kohli  7263.0    237.0
1  Rohit Sharma  6628.0    243.0
3  Shubman Gill  2790.0    103.0

In [30]:
# 3.For the 'runs' column in your IPL player stats DataFrame, use fillna() to replace missing values with the mean of the column. Print the updated column to verify the changes.

In [32]:
 df["runs"].mean()

np.float64(5440.75)

In [35]:
mean_runs = df["runs"].mean()

In [36]:
mean_runs

np.float64(5440.75)

In [37]:
df["runs"] = df["runs"].fillna(mean_runs)

In [38]:
df["runs"]

0    7263.00
1    6628.00
2    5082.00
3    2790.00
4    5440.75
Name: runs, dtype: float64

In [39]:
# 4.Simulate a Zomato-style restaurant ratings dataset with some missing ratings. Use forward fill (method='ffill') to fill missing values in the ratings column, then use backward fill (method='bfill') for any remaining missing values. Show the before and after results.

In [40]:
data = {"restaurant": ["A", "B", "C", "D", "E", "F"],
        "rating": [4.5, None, 3.8, None, None, 4.2]}

In [42]:
df = pd.DataFrame(data)

In [43]:
df

  restaurant  rating
0          A     4.5
1          B     NaN
2          C     3.8
3          D     NaN
4          E     NaN
5          F     4.2

In [47]:
df["rating"].ffill()

0    4.5
1    4.5
2    3.8
3    3.8
4    3.8
5    4.2
Name: rating, dtype: float64

In [48]:
df["rating"] = df["rating"].ffill()

In [49]:
df["rating"].bfill()

0    4.5
1    4.5
2    3.8
3    3.8
4    3.8
5    4.2
Name: rating, dtype: float64

In [50]:
df["rating"] = df["rating"].bfill()

In [51]:
df

  restaurant  rating
0          A     4.5
1          B     4.5
2          C     3.8
3          D     3.8
4          E     3.8
5          F     4.2

In [ ]:
# 5.Pick any one column with missing values from your dataset and explain which missingness mechanism (MCAR, MAR, or MNAR) is most likely and why, using 2-3 sentences.<br><br><em><strong>Hint:</strong> Think about whether the missing data is random or related to other factors in the dataset.</em>