In [1]:
import numpy as np
import pandas as pd

In [2]:
# 1.Download a small sample of your recent Zomato order history as a CSV (or create a mock CSV with restaurant names and order dates), then use pandas' duplicated() function to find and print any duplicate orders based on restaurant name and date.

In [4]:
data = {
    "restaurant": ["Dominos", "Swiggy Cafe", "Dominos", "Pizza Hut", "Swiggy Cafe"],
    "order_date": ["2026-08-20", "2026-08-21", "2026-08-20", "2026-08-22", "2026-08-21"]
}

In [5]:
data

{'restaurant': ['Dominos',
  'Swiggy Cafe',
  'Dominos',
  'Pizza Hut',
  'Swiggy Cafe'],
 'order_date': ['2026-08-20',
  '2026-08-21',
  '2026-08-20',
  '2026-08-22',
  '2026-08-21']}

In [6]:
df = pd.DataFrame(data)

In [7]:
df

    restaurant  order_date
0      Dominos  2026-08-20
1  Swiggy Cafe  2026-08-21
2      Dominos  2026-08-20
3    Pizza Hut  2026-08-22
4  Swiggy Cafe  2026-08-21

In [8]:
 df[df.duplicated(subset=["restaurant", "order_date"], keep=False)]

    restaurant  order_date
0      Dominos  2026-08-20
1  Swiggy Cafe  2026-08-21
2      Dominos  2026-08-20
4  Swiggy Cafe  2026-08-21

In [9]:
# 2.Given a list of Flipkart product reviews with some duplicate entries, use value_counts() in pandas to identify which review texts are repeated most often and display the top 3 most common duplicate reviews.

In [10]:
pd.Series([
    "Good product",
    "Excellent quality",
    "Good product",
    "Nice product",
    "Good product",
    "Excellent quality",
    "Nice product",
    "Excellent quality",
    "Excellent quality"
])

0         Good product
1    Excellent quality
2         Good product
3         Nice product
4         Good product
5    Excellent quality
6         Nice product
7    Excellent quality
8    Excellent quality
dtype: str

In [11]:
reviews = pd.Series([
    "Good product",
    "Excellent quality",
    "Good product",
    "Nice product",
    "Good product",
    "Excellent quality",
    "Nice product",
    "Excellent quality",
    "Excellent quality"
])

In [12]:
reviews

0         Good product
1    Excellent quality
2         Good product
3         Nice product
4         Good product
5    Excellent quality
6         Nice product
7    Excellent quality
8    Excellent quality
dtype: str

In [13]:
 reviews.value_counts()

Excellent quality    4
Good product         3
Nice product         2
Name: count, dtype: int64

In [14]:
# 3.Create a DataFrame with mock data for Spotify playlists, including playlist names and creator usernames, where some rows are exact duplicates. Use drop_duplicates() to remove duplicate playlists and print the cleaned DataFrame.

In [16]:
pd.DataFrame({
    "playlist_name": ["Workout Hits", "Chill Songs", "Workout Hits", "Party Songs"],
    "creator": ["Bhumi", "Riya", "Bhumi", "Anita"] })

  playlist_name creator
0  Workout Hits   Bhumi
1   Chill Songs    Riya
2  Workout Hits   Bhumi
3   Party Songs   Anita

In [17]:
df = pd.DataFrame({
    "playlist_name": ["Workout Hits", "Chill Songs", "Workout Hits", "Party Songs"],
    "creator": ["Bhumi", "Riya", "Bhumi", "Anita"]
})

In [18]:
df

  playlist_name creator
0  Workout Hits   Bhumi
1   Chill Songs    Riya
2  Workout Hits   Bhumi
3   Party Songs   Anita

In [19]:
df.drop_duplicates()

  playlist_name creator
0  Workout Hits   Bhumi
1   Chill Songs    Riya
3   Party Songs   Anita

In [20]:
# 4.Suppose you have a DataFrame of Instagram usernames where some entries have typos (like 'insta_queen', 'insta-queen', 'instaqueen'). Use the replace() function to standardize all these variants to 'instaqueen'.

In [21]:
pd.DataFrame({
    "username": [
        "insta_queen",
        "insta-queen",
        "instaqueen",
        "insta_queen",
        "insta-queen"
    ]
})

      username
0  insta_queen
1  insta-queen
2   instaqueen
3  insta_queen
4  insta-queen

In [22]:
df = pd.DataFrame({
    "username": [
        "insta_queen",
        "insta-queen",
        "instaqueen",
        "insta_queen",
        "insta-queen"
    ]
})

In [23]:
df

      username
0  insta_queen
1  insta-queen
2   instaqueen
3  insta_queen
4  insta-queen

In [24]:
df["username"].replace({
    "insta_queen": "instaqueen",
    "insta-queen": "instaqueen",
    "instaqueen": "instaqueen"
})

0    instaqueen
1    instaqueen
2    instaqueen
3    instaqueen
4    instaqueen
Name: username, dtype: str

In [25]:
# 5.You have a DataFrame column for payment status from a Paytm-like app with mixed values: 'Yes', 'yes', 'Y', 'No', 'no', 'N', and some with extra spaces. Write code to unify this column so all paid statuses become 1 and all unpaid statuses become 0, trimming whitespace and fixing capitalization where needed.<br><br><em><strong>Hint:</strong> Use str.strip(), str.lower(), and map/replace methods in pandas.</em>

In [26]:
pd.DataFrame({
    "payment_status": ["Yes", " yes ", "Y", "No", " no ", "N", " YES "]
})

  payment_status
0            Yes
1           yes
2              Y
3             No
4            no
5              N
6           YES

In [28]:
df = pd.DataFrame({
    "payment_status": ["Yes", " yes ", "Y", "No", " no ", "N", " YES "]
})

In [29]:
df

  payment_status
0            Yes
1           yes
2              Y
3             No
4            no
5              N
6           YES

In [30]:
df["payment_status"].str.strip().str.lower()

0    yes
1    yes
2      y
3     no
4     no
5      n
6    yes
Name: payment_status, dtype: str

In [32]:
df["payment_status"] = df["payment_status"].str.strip().str.lower()

In [33]:
df["payment_status"]

0    yes
1    yes
2      y
3     no
4     no
5      n
6    yes
Name: payment_status, dtype: str

In [34]:
df["payment_status"] = df["payment_status"].replace({
    "yes": 1,
    "y": 1,
    "no": 0,
    "n": 0
})

In [35]:
df["payment_status"]

0    1
1    1
2    1
3    0
4    0
5    0
6    1
Name: payment_status, dtype: object